package uk.org.peltast.ald.models;

public enum ArmyListConstants {ARMY_ID, ARMY_BOOK, ARMY_COSTFILE, ARMY_NAME, ARMY_YEAR,
	ROW_QTY, ROW_DESC, ROW_DRILL, ROW_TYPE, ROW_GRADE, ROW_ADJ, ROW_TROOP_COST, ROW_LINE_COST, ROW_CMD1_QTY, ROW_CMD2_QTY, ROW_CMD3_QTY, ROW_CMD4_QTY, ROW_UNUSED,
	ARMY_EL_COUNT, ARMY_EL_EQUIV, ARMY_HALF, ARMY_POINTS,
	CMD1_COST, CMD2_COST, CMD3_COST, CMD4_COST, 
	CMD1_EL_COUNT, CMD2_EL_COUNT, CMD3_EL_COUNT, CMD4_EL_COUNT,
	CMD1_EQUIV, CMD2_EQUIV, CMD3_EQUIV, CMD4_EQUIV,
	CMD1_BP, CMD2_BP, CMD3_BP, CMD4_BP}
